### ISSUE TITLE
result temporary variable shadowed in seasideProcessRequest:adaptor:resultBlock:

### ISSUE THREAD

**Issue by jbrichau** [GsDevKit/Seaside31#66]
The method begins with:
```
	| result |
	[ | retryCount result count |
```
The ```result``` temporary var is shadowed. Which seems problematic because it's being returned at the end of the method.

**Comment by jbrichau** [comment]
I dug back to Seaside3.0 where it already seems to be the case, @dalehenrich any black magic reason for this? Seems like this is not supposed to work...?

**Comment by jbrichau** [comment]
In the end, this was never an issue because there is no code path to the return statement in the last line of this method.

**Comment by dalehenrich** [comment]
fixed in PR #67
