### ISSUE TITLE
PR #74 introduced load order problem

### ISSUE THREAD

**Issue by dalehenrich** [GsDevKit/Seaside31#75]
see discussion in PR #74 - https://github.com/GsDevKit/Seaside31/pull/74#issuecomment-109352409

**Comment by dalehenrich** [comment]
In a nutshell:

> rename WAObjectLogDebuggerWalkback to WAGemStoneContinuationDebugger and move from package WAGemStoneContinuationDebugger to Seaside-GemStone-Development

**Comment by marianopeck** [comment]
Yes!

**Comment by dalehenrich** [comment]
[full tests green](https://travis-ci.org/GsDevKit/Seaside31/builds/65646667)
